---

- name: Create Root ssh directory
  file: path=/root/.ssh state=directory recurse=yes owner=root group=root

- name: Install deploy ssh key
  template: src=app.deploy dest=/root/.ssh/app.deploy owner=root group=root mode=0600

- name: Set ssh config
  copy: src=ssh_config dest=/root/.ssh/config owner=root group=root mode=0664
