---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install common software
  apt: name={{ item }} state=present
  with_items:
    - htop
    - nload
    - git
    - make
    - python-pip
