---

  - name: create docker path
    file: path=/opt/docker state=directory

  - name: copy dockerfile
    copy: src=docker/ dest=/opt/docker mode=755

  - name: build nginx
    docker_image: path=/opt/docker/nginx/ name=abraham/nginx state=build

  - name: build ruby
    docker_image: path=/opt/docker/ruby/ name=abraham/ruby state=build

  - name: run nginx servers
    docker: image=abraham/nginx count=3
